spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://ec2-15-164-67-216.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/google"
          naver:
            redirect-uri: "http://ec2-15-164-67-216.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/naver"

app:
  oauth2:
    redirect-base-url: "http://ec2-15-164-67-216.ap-northeast-2.compute.amazonaws.com:8080/api/auth/test"